name: Publish to pub.dev

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish:
    permissions:
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@03a180dbe1de8ea7fb700663cbb7d24ca4bbe82c
