name: Publish to pub.dev

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish:
    permissions:
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@92cfcc5b56b5f03d4418281fd5b0ae0dacbfd9fa
