name: Publish to pub.dev

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish:
    permissions:
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@6e0ff0bc3a029a9532ae6a86b1ea4906038921bc
